<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Nat" Version="3.0.1" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.0.1641" />
    <PackageReference Include="NetCoreServer" Version="5.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Tinn" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Content\empty.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\font.spritefont">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\red.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Content\test.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
